from . import school_teacher
from . import school_score
from . import school_student
from . import school_student_history
from . import school_subject
from . import school_class
from . import school_score
from . import school_lichthi
from . import res_users
